input: [
    'resources/css/main.css',
    'resources/css/auth/signin.css',
    'resources/css/auth/signup.css',
    'resources/css/user/beranda.css',
    'resources/css/user/profile.css',
    'resources/css/user/editprofile.css',
    'resources/css/user/tambahposting.css',
    'resources/css/user/riwayatposting.css',
    'resources/css/user/editposting.css',
    'resources/css/user/notifikasi.css',
    'resources/css/user/riwayatlapor.css',
    'resources/css/admin/dashboardAdmin.css',
    'resources/css/admin/berandaAdmin.css',
],